//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IupMetadata.CodeGenerators.Zig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etinterop.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IupMetadata.CodeGenerators.Zig.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const std = @import(&quot;std&quot;);
        ///
        ///const c = @import(&quot;../interop.zig&quot;);
        ///const iup = @import(&quot;../iup.zig&quot;);
        ///const traits = @import(&quot;../traits.zig&quot;);
        ///
        ///const debug = std.debug;
        ///const trait = std.meta.trait;
        ///
        ///const Element = iup.Element;
        ///const Error = iup.Error;
        ///const ChildrenIterator = iup.ChildrenIterator;
        ///const Size = iup.Size;
        ///const Margin = iup.Margin;
        ///
        ///{{ElementDocumentation}}
        ///pub const {{Name}} = opaque {
        ///    pub const CLASS_NAME = &quot;{{ClassName}}&quot;;
        ///    const Self = @This();
        ///
        ///    {{CallbacksDecl}} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string element {
            get {
                return ResourceManager.GetString("element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const std = @import(&quot;std&quot;);
        ///const ascii = std.ascii;
        ///const testing = std.testing;
        ///
        ///const iup = @import(&quot;iup.zig&quot;);
        ///const c = @import(&quot;interop.zig&quot;);
        ///const ChildrenIterator = iup.ChildrenIterator;
        ///
        ///{{Imports}}
        ///
        //////
        ////// IUP contains several user interface elements.
        ////// The library’s main characteristic is the use of native elements.
        ////// This means that the drawing and management of a button or text box is done by the native interface system, not by IUP.
        ////// This makes the application’s appearance more [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
    }
}
